services:
  - postgresql
sudo: false
language: ruby
rvm:
  - 2.6.4
cache: bundler
before_script:
  - psql -c 'create database textbook_test;' -U postgres
before_install:
  # - gem update --system
  # - gem install bundler
  - gem update bundler # added
  - gem --version
  - wget http://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
  - google-chrome-stable --headless --no-sandbox
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: wMoEfuwYGWwcR/YXmc6vXawJqxT6Zo8xJxwZcUqkPjCvSG+SydM7kz2FjInFaiGnoWbhVpvF3WmdqAujaJwhEFI0r2p4WZ8BxvusdCFuVghV55QjrfVe4bzsf9dabYDEK2b8tm51xZZzkULwwA30tcURG5Pp1sz+yT7VH3VxAYs=
  app: learnhowtoprogram
  on:
    repo: epicodus/textbook
  run: "rake db:migrate"
addons:
  chrome: stable
