language: ruby
rvm:
  - 2.2.3
cache: bundler
before_script:
  - "bundle exec rake db:create db:schema:load"
deploy:
  provider: heroku
  api_key:
    secure: wMoEfuwYGWwcR/YXmc6vXawJqxT6Zo8xJxwZcUqkPjCvSG+SydM7kz2FjInFaiGnoWbhVpvF3WmdqAujaJwhEFI0r2p4WZ8BxvusdCFuVghV55QjrfVe4bzsf9dabYDEK2b8tm51xZZzkULwwA30tcURG5Pp1sz+yT7VH3VxAYs=
  app: learnhowtoprogram
  on:
    repo: epicodus/textbook
  run: "rake db:migrate"
